---
functional:
  - Пользователь должен иметь возможность провести игру без регистрации
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте используя email и пароль
  - Пользователь должен иметь возможность авторизоваться на сайте используя Github
  - Пользователь должен иметь возможность авторизоваться на сайте используя Discord
  - Пользователь должен иметь возможность восстановить пароль
  - На странице регистрации поле "Nickname" может содержать буквы, цифры и символы подчеркивания и должен начинаться с латинской
    буквы, а также содержать от 3 до 16 символов
  - На странице регистрации в поле "Email" должен быть валидный email 
  - Авторизованный пользователь должен иметь возможность писать в чат General 
  - Авторизованный пользователь должен иметь возможность создать игру, с другим авторизованным пользователем, другом или с ботом
  - Авторизованный пользователь должен иметь возможность выбирать игру по уровню сложности
  - Авторизованный Пользователь должен иметь возможность создать игру с таймером от 3 до 60 минут
  - Авторизованный пользователь должен иметь возможность выбрать задачу по тегу или по имени
  - Авторизованный пользователь должен иметь возможность следить за ходом игры другого авторизованным пользователя
  - Авторизованный пользователь должен иметь возможность присоединиться к созданной другим авторизованным пользователем игре
  - Авторизованный пользователь должен иметь возможность создавать турнир
  - Авторизованный пользователь должен иметь возможность просматривать уже созданные турниры
  - Авторизованный пользователь должен иметь возможность участвовать в уже созданных турнирах
  - Авторизованный пользователь должен иметь возможность фильтровать рейтинг игроков
  - Авторизованный пользователь должен иметь возможность завершить игру выполнив задание
  - Авторизованный пользователь должен иметь возможность завершить игру по истечению времени
  - Авторизованный пользователь должен иметь возможность сдаться во время игры
  - Авторизованный пользователь должен иметь возможность просматривать в записи завершенные игры
  - Авторизованный пользователь получает очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Все пользователи должны иметь возможность отправлять фидбек во время игры
  - Если во время игры один из игроков вылетел из игры, второй может продолжать 
    играть, а первый в любой момент, пока незакончена игра, может переподключиться в игру
  - Задачи в игре должны быть даны на двух языках — русском и английском
  - В игре должна быть возможность выбора языка программирования для выполнения заданной задачи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Находясь на странице игрока авторизованный пользователь может кинуть ему вызов в игру
  - Находясь на странице игрока авторизованный пользователь может написать ему личное сообщение
  - Находясь на странице регистрации неправильный ввод данных должен сразу подчеркиваться
  - Сайт должен быть локализован
  - Добавить кнопку "Send Feadback" в турнир
